services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - ../:/app
      - /app/node_modules
      - /app/media
    env_file:
      - ../.env.development
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - ../.env.development
