services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - ../:/app
      - /app/node_modules
    env_file:
      - ../.env.development
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - ../.env.development

  redis:
    image: redis
    env_file:
      - ../.env.development
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
